Static::Application.routes.draw do
  match "/templates/wrapper.html.erb", :to => "root#wrapper"
  match "/templates/wrapper_with_fat_footer.html.erb", :to => "root#wrapper_with_fat_footer"
  match "/templates/print.html.erb", :to => "root#print"
  match "/templates/related.raw.html.erb", :to => "root#related"
  match "/templates/homepage.html.erb", :to => "root#homepage"
  match "/templates/admin.html.erb", :to => "root#admin"
  match "/templates/404.html.erb", :to => "root#404"
  match "/templates/406.html.erb", :to => "root#406"
  match "/templates/418.html.erb", :to => "root#418"
  match "/templates/500.html.erb", :to => "root#500"
  match "/templates/501.html.erb", :to => "root#501"
  match "/templates/503.html.erb", :to => "root#503"
  match "/templates/504.html.erb", :to => "root#504"
end
